//! Compares the Rust log-mel implementation against a reference generated by
//! the HuggingFace WhisperFeatureExtractor numpy algorithm
//! (see tests/data/gen_mel_reference.py).

use qwen3_asr::mel::log_mel_spectrogram;

fn read_f32(path: &str) -> Vec<f32> {
    let bytes = std::fs::read(path).expect("reference file");
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

#[test]
fn matches_whisper_reference_within_tolerance() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data");
    let audio = read_f32(&format!("{dir}/mel_ref_input.f32"));
    let expected = read_f32(&format!("{dir}/mel_ref_expected.f32"));

    let mel = log_mel_spectrogram(&audio, 128, 100).expect("mel");
    assert_eq!(mel.n_frames, 200);
    assert_eq!(mel.n_valid_frames, 200);
    assert_eq!(mel.data.len(), expected.len());

    let mut max_abs_diff = 0.0f32;
    for (got, want) in mel.data.iter().zip(expected.iter()) {
        max_abs_diff = max_abs_diff.max((got - want).abs());
    }
    assert!(
        max_abs_diff < 1e-4,
        "max abs diff {max_abs_diff} exceeds 1e-4"
    );
}
